
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LSQ = 3;
  public static final int COLON = 5;
  public static final int NUMBER = 10;
  public static final int TRUE = 12;
  public static final int NULL = 9;
  public static final int RSQ = 4;
  public static final int EOF = 0;
  public static final int FALSE = 13;
  public static final int error = 1;
  public static final int COMMA = 6;
  public static final int RCURLY = 8;
  public static final int QUOTE = 2;
  public static final int LCURLY = 7;
  public static final int CHAR = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "QUOTE",
  "LSQ",
  "RSQ",
  "COLON",
  "COMMA",
  "LCURLY",
  "RCURLY",
  "NULL",
  "NUMBER",
  "CHAR",
  "TRUE",
  "FALSE"
  };
}

